### =================================================================
### TESTES DAS ROTAS DE DONOS
### =================================================================

### 1. Listar todos os donos
GET http://127.0.0
Accept: application/json

###

### 2. Buscar um dono específico por ID (Ex: ID 1)
GET http://127.0.0/1
Accept: application/json

###

### 3. Cadastrar um novo dono
POST http://127.0.0
Content-Type: application/json

{
    "nome": "Carlos Souza",
    "telefone": "45999887766"
}

###

### 4. Atualizar os dados de um dono (Ex: ID 1)
PUT http://127.0.0/1
Content-Type: application/json

{
    "nome": "Ana Paula Ribeiro Silva",
    "telefone": "45999110001"
}

###

### 5. Deletar um dono (Ex: ID 3)
DELETE http://127.0.0/3


### =================================================================
### TESTES DAS ROTAS DE PETS
### =================================================================

### 6. Listar todos os pets (mostra o nome do dono automaticamente)
GET http://127.0.0
Accept: application/json

###

### 7. Buscar um pet específico por ID (Ex: ID 1)
GET http://127.0.0/1
Accept: application/json

###

### 8. Cadastrar un novo pet (Vinculado ao dono ID 1)
POST http://127.0.0
Content-Type: application/json

{
    "nome": "Mel",
    "especie": "gato",
    "idade": 3,
    "dono_id": 1
}

###

### 9. Atualizar os dados de um pet (Ex: ID 1)
PUT http://127.0.0/1
Content-Type: application/json

{
    "nome": "Rex Antigo",
    "especie": "cachorro",
    "idade": 5
}

###

### 10. Deletar um pet (Ex: ID 3)
DELETE http://127.0.0/3
